<?xml version="1.0"?>
<!DOCTYPE package [
<!ELEMENT packages (package)*>
<!ELEMENT package (packages*, classes*)>
<!ATTLIST package name    CDATA #REQUIRED>
<!ELEMENT classes (class)*>
<!ELEMENT class (fields?,  methods?)>
<!ATTLIST class	name		CDATA	#REQUIRED
				visibility	CDATA	#REQUIRED
				static		CDATA	"true"
				abstract	CDATA	"false"
				final		CDATA	"false"
				interface	CDATA	#REQUIRED>
<!ELEMENT fields (field)*>
<!ELEMENT field (type)>
<!ATTLIST field name		CDATA	#REQUIRED
				visibility	CDATA	#REQUIRED
				static		CDATA	"false"
				final		CDATA	#REQUIRED
				transient	CDATA	"false"
				volatile	CDATA	"false">
<!ELEMENT type (class)>
<!ELEMENT methods (method)*>
<!ELEMENT method (parametertypes, returntype, exceptiontypes)>
<!ATTLIST method	name			CDATA	#REQUIRED
					visibility		CDATA	#REQUIRED
					static			CDATA	"false"
					final			CDATA	"false"
					abstract		CDATA	"false"
					synchronized	CDATA	"false">
<!ELEMENT parametertypes (class)*>
<!ELEMENT returntype (class)>
<!ELEMENT exceptiontypes (class)*>
]>
<package name="java.lang">
  <packages>
    <package name="java.lang.reflect">
      <packages/>
      <classes>
        <class name="java.lang.reflect.GenericDeclaration" visibility="public" static="false" abstract="true" final="false" interface="true">
          <fields/>
          <methods>
            <method name="getTypeParameters" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes/>
              <returntype>
                <class name="java.lang.reflect.TypeVariable[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getAnnotation" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
				</class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation" visibility="public" static="false" abstract="true" final="false" interface="true">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getAnnotations" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getAnnotationsByType" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getDeclaredAnnotation" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation" visibility="public" static="false" abstract="true" final="false" interface="true">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getDeclaredAnnotations" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getDeclaredAnnotationsByType" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="isAnnotationPresent" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="boolean" visibility="public" static="false" abstract="true" final="true" interface="false">
                  <fields/>
                  <methods>
                  </methods>
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
          </methods>
        </class>
        <class name="java.lang.reflect.AnnotatedElement" visibility="public" static="false" abstract="true" final="false" interface="true">
          <fields/>
          <methods>
            <method name="getAnnotation" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation" visibility="public" static="false" abstract="true" final="false" interface="true">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getAnnotations" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getAnnotationsByType" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getDeclaredAnnotation" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation" visibility="public" static="false" abstract="true" final="false" interface="true">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getDeclaredAnnotations" visibility="public" static="false" final="false" abstract="true" synchronized="false">
              <parametertypes>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="getDeclaredAnnotationsByType" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="java.lang.annotation.Annotation[]" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
            <method name="isAnnotationPresent" visibility="public" static="false" final="false" abstract="false" synchronized="false">
              <parametertypes>
                <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
                </class>
              </parametertypes>
              <returntype>
                <class name="boolean" visibility="public" static="false" abstract="true" final="true" interface="false">
                </class>
              </returntype>
              <exceptiontypes>
              </exceptiontypes>
            </method>
          </methods>
        </class>
        <class name="java.lang.reflect.Type" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.AccessibleObject" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.Field" visibility="public" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.Member" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.Parameter" visibility="public" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.Method" visibility="public" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.Executable" visibility="public" static="false" abstract="true" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.Constructor" visibility="public" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.ReflectPermission" visibility="public" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.Modifier" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.ReflectAccess" visibility="package private" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.Array" visibility="public" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.InvocationTargetException" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.Proxy" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.InvocationHandler" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.WeakCache" visibility="package private" static="false" abstract="false" final="true" interface="false">
        </class>
        <class name="java.lang.reflect.WildcardType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.UndeclaredThrowableException" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.TypeVariable" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.ParameterizedType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.MalformedParametersException" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.MalformedParameterizedTypeException" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.GenericSignatureFormatError" visibility="public" static="false" abstract="false" final="false" interface="false">
        </class>
        <class name="java.lang.reflect.GenericArrayType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.AnnotatedWildcardType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.AnnotatedTypeVariable" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.AnnotatedType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.AnnotatedParameterizedType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
        <class name="java.lang.reflect.AnnotatedArrayType" visibility="public" static="false" abstract="true" final="false" interface="true">
        </class>
      </classes>
    </package>
  </packages>
  <classes>
    <class name="java.lang.Object" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.String" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Comparable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.CharSequence" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.Class" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Cloneable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.ClassLoader" visibility="public" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.System" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Throwable" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Error" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ThreadDeath" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Exception" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.RuntimeException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.SecurityManager" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ClassNotFoundException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ReflectiveOperationException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.NoClassDefFoundError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.LinkageError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ClassCastException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ArrayStoreException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.VirtualMachineError" visibility="public" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.OutOfMemoryError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.StackOverflowError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IllegalMonitorStateException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Thread" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Runnable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.ThreadGroup" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.BootstrapMethodError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.StringBuffer" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.AbstractStringBuilder" visibility="package private" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.Appendable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.StringBuilder" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.AutoCloseable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.StackTraceElement" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Boolean" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Character" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Float" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Number" visibility="public" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.Double" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Byte" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Short" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Integer" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Long" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.NullPointerException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ArithmeticException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.RuntimePermission" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Iterable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.Math" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Runtime" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.NoSuchMethodError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IncompatibleClassChangeError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ThreadLocal" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Enum" visibility="public" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.Terminator" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IllegalArgumentException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Compiler" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Readable" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.CharacterData" visibility="package private" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.CharacterDataLatin1" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.SystemClassLoaderAction" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ClassValue" visibility="public" static="false" abstract="true" final="false" interface="false">
    </class>
    <class name="java.lang.ProcessEnvironment" visibility="package private" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.StringCoding" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.InterruptedException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Void" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.NoSuchMethodException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.InstantiationException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.NoSuchFieldException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.NoSuchFieldError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IllegalAccessException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IllegalStateException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ApplicationShutdownHooks" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Shutdown" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.UnsupportedOperationException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.Package" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.SecurityException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.NumberFormatException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IndexOutOfBoundsException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.CloneNotSupportedException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.InternalError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.UnsatisfiedLinkError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ClassLoaderHelper" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ClassFormatError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ArrayIndexOutOfBoundsException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.StringIndexOutOfBoundsException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.ExceptionInInitializerError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.CharacterData00" visibility="package private" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.InheritableThreadLocal" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.StrictMath" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.IllegalAccessError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.VerifyError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.UnsupportedClassVersionError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.UnknownError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.TypeNotPresentException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.SuppressWarnings" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.SafeVarargs" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.ProcessImpl" visibility="package private" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.ProcessBuilder" visibility="public" static="false" abstract="false" final="true" interface="false">
    </class>
    <class name="java.lang.Override" visibility="public" static="false" abstract="true" final="false" interface="true">
    </class>
    <class name="java.lang.NegativeArraySizeException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.InstantiationError" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>
    <class name="java.lang.IllegalThreadStateException" visibility="public" static="false" abstract="false" final="false" interface="false">
    </class>